ThuanTanUmbraco/Models/ContactForm.cs
using ThuanTanUmbraco.ClassHelper;

namespace ThuanTanUmbraco.Models
{
    public class ContactForm
    {
        [UmbracoDisplay("Form.Field.Name")]
        [UmbracoRequired("Form.Field.Name.Required")]
        public string Name { get; set; }
        [UmbracoDisplay("Form.Field.Email")]
        [UmbracoRequired("Form.Field.Email.Required")]
        [UmbracoEmail("Form.Field.Email.Validation")]
        public string Email { get; set; }
        [UmbracoDisplay("Form.Field.Phone")]
        [UmbracoRequired("Form.Field.Phone.Required")]
        public string Phone { get; set; }
        [UmbracoDisplay("Form.Field.Message")]
        [UmbracoRequired("Form.Field.Message.Required")]
        public string Message { get; set; }
        public string ErrorMsg { get; set; }
        public int CultureLCID { get; set; }
    }
}

ThuanTanUmbraco/Controllers/SiteController.cs
using System;
using System.Net.Mail;
using System.Web.Configuration;
using System.Web.Mvc;
using ThuanTanUmbraco.Models;
using Umbraco.Web.Mvc;

namespace ThuanTanUmbraco.Controllers
{
    public class SiteController : SurfaceController
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult HandleContactForm(ContactForm model)
        {
            //System.Threading.Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo(model.CultureLCID);
            if (!ModelState.IsValid)
            {
                model.ErrorMsg = Umbraco.GetDictionaryValue("Send.Failure");
                return PartialView("~/Views/Partials/Contact/_Form.cshtml", model);
            }
            var domainName = Request.Url?.GetLeftPart(UriPartial.Authority);
            var emailReceive = WebConfigurationManager.AppSettings["EmailContactReceive"];
            var messageString = "<h3>" + domainName + " LIÊN HỆ</h3>";
            messageString += "<b>Họ Tên: </b>" + model.Name + "<br />";
            messageString += "<b>Email: </b>" + model.Email + "<br />";
            messageString += "<b>Điện thoại: </b>" + model.Phone + "<br />";
            messageString += "<b>Nội dung tin nhắn: </b>" + model.Message;
            var email = new MailMessage
            {
                Subject = "Nội dung liên hệ",
                Body = messageString,
                IsBodyHtml = true,
                To = { emailReceive }
            };
            try
            {
                //Connect to SMTP credentials set in web.config
                var smtp = new SmtpClient();

                //Try & send the email with the SMTP settings
                smtp.Send(email);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            model.Name = "";
            model.Email = "";
            model.Phone = "";
            model.Message = "";
            model.ErrorMsg = Umbraco.GetDictionaryValue("Send.Success");
            ModelState.Clear();
            return PartialView("~/Views/Partials/Contact/_Form.cshtml", model);
        }
    }
}

ThuanTanUmbraco/Views/Partials/Contact/_Contact.cshtml
@inherits UmbracoViewPage<ThuanTanUmbraco.Models.ContactForm>
@{
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
    // Get the current page
    //IPublishedContent objModel = Umbraco.TypedContent(UmbracoContext.Current.PageId);

    // Tells the controller what page to add a comment under.
    //Model.CultureLCID = System.Globalization.CultureInfo.CurrentUICulture.LCID;
    //var langCode = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
}
@using (Ajax.BeginForm("HandleContactForm", "Site", null, new AjaxOptions { UpdateTargetId = "contentAjaxForm", HttpMethod = "POST", OnSuccess = "onSuccess", OnFailure = "onFailure" }, new { id = "contactForm", @class = "ajaxForm" }))
{
    <div id="contentAjaxForm">
        @Html.Partial("~/Views/Partials/Contact/_Form.cshtml", Model)
    </div>
}

ThuanTanUmbraco/Views/Partials/Contact/_Form.cshtml
@inherits UmbracoViewPage<ThuanTanUmbraco.Models.ContactForm>
@{
    if (!string.IsNullOrEmpty(Model.ErrorMsg))
    {
        <div id="divUpdateMessage">
            @Model.ErrorMsg
        </div>
    }
}
@Html.AntiForgeryToken()
<div class="wrap-send">
    <div class="contact-w">
        <div class="contact-input">
            @Html.TextBoxFor(model => model.Name, new { @class = "contact-textbox", placeholder = Umbraco.GetDictionaryValue("Form.Field.Name") })
            @Html.ValidationMessageFor(x => x.Name)
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="contact-w">
                <div class="contact-input">
                    @Html.TextBoxFor(model => model.Email, new { @class = "contact-textbox", placeholder = "Email" })
                    @Html.ValidationMessageFor(x => x.Email)
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="contact-w">
                <div class="contact-input">
                    @Html.TextBoxFor(model => model.Phone, new { @class = "contact-textbox", placeholder = Umbraco.GetDictionaryValue("Form.Field.Phone") })
                    @Html.ValidationMessageFor(x => x.Phone)
                </div>
            </div>
        </div>
    </div>
    <div class="contact-w">
        <div class="contact-input">
            @Html.TextAreaFor(model => model.Message, new { @class = "contact-area", placeholder = Umbraco.GetDictionaryValue("Form.Field.Message") })
            @Html.ValidationMessageFor(x => x.Message)
        </div>
    </div>
    <div class="contact-w">
        <div class="contact-btn">
            <input type="submit" class="button-btn" name="" value="@Umbraco.GetDictionaryValue("Send")" />
        </div>
    </div>
</div>
@Html.HiddenFor(x => x.CultureLCID)
<div class="loading_div"></div>