ThuanTanUmbraco/Models/Cart.cs
namespace ThuanTanUmbraco.Models
{
    public class CartItem
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Url { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
    }
}

ThuanTanUmbraco/Controllers/CartController.cs
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ThuanTanUmbraco.Models;
using Umbraco.Core.Models;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace ThuanTanUmbraco.Controllers
{
    public class CartController : SurfaceController
    {
        public ActionResult InitCart()
        {
            var listCart = new List<CartItem>();
            if (Session["Cart"] != null)
            {
                listCart = (List<CartItem>)Session["Cart"];
            }
            return PartialView("~/Views/Partials/Cart/_CartItem.cshtml", listCart);
        }
        public ActionResult RenderCartItem(string model)
        {
            var cart = new JavaScriptSerializer().Deserialize<List<CartItem>>(model);
            return PartialView("~/Views/Partials/Cart/_CartItem.cshtml", cart);
        }
        public ActionResult RenderCartDetail()
        {
            var cart = new List<CartItem>();
            if (Session["Cart"] != null)
            {
                cart = (List<CartItem>)Session["Cart"];
                Session["Cart"] = cart;
            }
            return PartialView("~/Views/Partials/Cart/CartDetail/_Cart.cshtml", cart);
        }
        public ActionResult KeepShopping()
        {
            var culture = CultureInfo.CurrentCulture;
            var currentHomePage = Services.ContentService.GetRootContent().First(x => x.GetCulture().Name == culture.Name);
            var url = "/";
            if (currentHomePage != null)
            {
                url = new RenderModel(Umbraco.TypedContent(currentHomePage.Id), culture).Content.Url;
            }
            return Json(new { link = url }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GoToPayment()
        {
            var culture = CultureInfo.CurrentCulture;
            var currentHomePage = Services.ContentService.GetRootContent().First(x => x.GetCulture().Name == culture.Name);
            var url = "/checkout";
            var checkout = currentHomePage?.Children().FirstOrDefault(x => x.ContentType.Alias == "checkOut");
            if (checkout != null)
            {
                url = new RenderModel(Umbraco.TypedContent(checkout.Id), culture).Content.Url;
            }
            return Json(new {link = url }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult UpdateTotalPrice(int id, int quantity)
        {
            var total = 0;
            if (Session["Cart"] != null)
            {
                var listCart = (List<CartItem>)Session["Cart"];
                var item = listCart.SingleOrDefault(x => x.Id == id);
                if (item != null)
                {
                    item.Quantity = quantity > 0 ? quantity : item.Quantity += 1;
                }
                total = listCart.Sum(x => (x.Price * x.Quantity));
                Session["Cart"] = listCart;
            }
            return Json(new { total = total }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public void AddToCart(string model)
        {
            var list = new JavaScriptSerializer().Deserialize<List<CartItem>>(model);
            Session["Cart"] = list;
        }
        [HttpPost]
        public ActionResult DeleteCartItem(int id, string color)
        {
            var itemPrice = 0;
            if (Session["Cart"] != null)
            {
                var listCart = (List<CartItem>)Session["Cart"];
                var item = listCart.SingleOrDefault(x => x.Id == id && x.Color.Trim().Replace(" ", "") == color.Trim().Replace(" ", ""));
                if (item != null)
                {
                    itemPrice = item.Price * item.Quantity;
                    listCart.Remove(item);
                }
                Session["Cart"] = listCart;
            }
            return Json(new { price = itemPrice }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult DeleteAllCart()
        {
            var cart = new List<CartItem>();
            Session["Cart"] = cart;
            return PartialView("~/Views/Partials/Cart/CartDetail/_Cart.cshtml", cart);
        }
    }
}

ThuanTanUmbraco/Controllers/CheckOutController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using ThuanTan.Entity.Context;
using ThuanTan.Entity.Models;
using ThuanTanUmbraco.Models;
using Umbraco.Web.Mvc;

namespace ThuanTanUmbraco.Controllers
{
    public class CheckOutController : SurfaceController
    {
        private ThuanTanContext db = new ThuanTanContext();
        public ActionResult CheckSessionCart()
        {
            var checkOut = new CheckOut();
            if (Session["Cart"] != null)
            {
                checkOut.CartItems = (List<CartItem>)Session["Cart"];
                Session["Cart"] = checkOut.CartItems;
            }
            return PartialView("~/Views/Partials/Checkout/_checkout.cshtml", checkOut);
        }
        [HttpPost]
        public ActionResult CheckOut(CheckOut model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return PartialView("~/Views/Partials/Checkout/_Form.cshtml", model);
                }
                var cartModel = new Cart
                {
                    MemberId = model.MemberId,
                    Name = model.Name,
                    Email = model.Email,
                    PhoneNumber = model.PhoneNumber,
                    Address = model.Address,
                    Note = model.Note,
                    PaymentMethods = model.PaymentMethods,
                    CreateDate = DateTime.Now
                };
                db.Carts.Add(cartModel);
                db.SaveChanges();
                if (model.CartItems != null && model.CartItems.Count > 0)
                {
                    var cartId = cartModel.Id;
                    foreach (var item in model.CartItems)
                    {
                        var productCart = new ProductCart
                        {
                            CartId = cartId,
                            Quantity = item.Quantity,
                            ProductId = item.Id,
                            Price = item.Price,
                            Color = item.Color
                        };
                        db.ProductCarts.Add(productCart);
                    }
                    db.SaveChanges();
                }
                model.IsSuccess = true;
                Session["Cart"] = null;
                return PartialView("~/Views/Partials/Checkout/_Form.cshtml", model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }
}

ThuanTanUmbraco/Controllers/MemberFrontEndController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThuanTanUmbraco.ClassHelper;
using ThuanTanUmbraco.Models;
using Umbraco.Core.Models;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace ThuanTanUmbraco.Controllers
{
    public class MemberFrontEndController : SurfaceController
    {
        [HttpPost]
        public ActionResult MemberLogin(LoginForm model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return PartialView("~/Views/Partials/User/Login/_Form.cshtml", model);
                }
                var member = Services.MemberService.GetByEmail(model.Username);
                if (member != null && member.IsApproved)
                {
                    var culture = CultureInfo.CurrentCulture;
                    var currentHomePage = Services.ContentService.GetRootContent().First(x => x.GetCulture().Name == culture.Name);
                    var link = "/";
                    if (currentHomePage != null)
                    {
                        link = new RenderModel(Umbraco.TypedContent(currentHomePage.Id), culture).Content.Url;
                    }
                    if (!Members.Login(model.Username, model.Password))
                    {
                        model.IsSuccess = false;
                        model.IsRunScripts = true;
                        model.ResponseText = Umbraco.GetDictionaryValue("Login.Failure");
                        model.ResponseHeader = "Error!!";
                        return PartialView("~/Views/Partials/User/Login/_Form.cshtml", model);
                    }
                    model.IsSuccess = true;
                    model.IsRunScripts = true;
                    model.ResponseText = Umbraco.GetDictionaryValue("Login.Success");
                    model.ResponseHeader = "Success!!";
                    model.RedirectLink = link;
                    return PartialView("~/Views/Partials/User/Login/_Form.cshtml", model);
                }
                model.IsSuccess = false;
                model.IsRunScripts = true;
                model.ResponseText = Umbraco.GetDictionaryValue("Account.NotExits");
                model.ResponseHeader = "Error!!";
                return PartialView("~/Views/Partials/User/Login/_Form.cshtml", model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
        [HttpPost]
        public ActionResult MemberForgotPassword(ResetPasswordForm model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return PartialView("~/Views/Partials/User/ForgotPassword/_Form.cshtml", model);
                }
                var member = Services.MemberService.GetByEmail(model.Email);
                if (member != null && member.IsApproved)
                {
                    var newPassword = Utils.CreateRandomPassword(10);
                    Services.MemberService.SavePassword(member, newPassword);
                    BackgroundJobs.SendMail.EnqueueForgotPassword(model.Email, Umbraco.GetDictionaryValue("Title.ResetPassword"), newPassword);
                    model.IsSuccess = true;
                    model.ResponseText = Umbraco.GetDictionaryValue("SendMail.NewPassword.Success");
                    return PartialView("~/Views/Partials/User/ForgotPassword/_Form.cshtml", model);
                }
                model.IsSuccess = false;
                model.ResponseText = Umbraco.GetDictionaryValue("Account.NotExits");
                return PartialView("~/Views/Partials/User/ForgotPassword/_Form.cshtml", model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        public ActionResult MemberSignUp(RegisterForm model)
        {
            try
            {
                var domainName = Request.Url?.GetLeftPart(UriPartial.Authority);
                var culture = CultureInfo.CurrentCulture;
                var currentHomePage = Services.ContentService.GetRootContent().First(x => x.GetCulture().Name == culture.Name);
                var verifySignUp = currentHomePage?.Children().FirstOrDefault(x => x.ContentType.Alias == "memberInfo")?.Children().FirstOrDefault(x => x.ContentType.Alias == "verifySignUp");
                var verifyLink = "";
                if (verifySignUp != null)
                {
                    verifyLink = new RenderModel(Umbraco.TypedContent(verifySignUp.Id), culture).Content.Url;
                }
                if (model.IsSendMail == false)
                {
                    if (!ModelState.IsValid)
                    {
                        return PartialView("~/Views/Partials/User/SignUp/_Form.cshtml", model);
                    }
                    var member = Services.MemberService.GetByEmail(model.Username);
                    if (member == null)
                    {
                        var newMember = Services.MemberService.CreateMember(model.Username, model.Username, model.FirstName + " " + model.LastName, "Member");
                        newMember.SetValue("firstName", model.FirstName);
                        newMember.SetValue("lastName", model.LastName);
                        newMember.SetValue("phoneNumber", model.PhoneNumber);
                        newMember.SetValue("address", model.Address);
                        newMember.IsApproved = false;
                        newMember.Name = model.FirstName + " " + model.LastName;
                        Services.MemberService.Save(newMember);
                        Services.MemberService.SavePassword(newMember, model.Password);
                        model.IsRegisterSuccess = true;
                        model.IsSendMail = true;
                        BackgroundJobs.SendMail.EnqueueRegister(model.Username, "Email xác nhận tài khoản", domainName, verifyLink);
                        return PartialView("~/Views/Partials/User/SignUp/_Form.cshtml", model);
                    }
                    model.IsRegisterSuccess = false;
                    model.ResponseText = Umbraco.GetDictionaryValue("Email.Exits");
                    return PartialView("~/Views/Partials/User/SignUp/_Form.cshtml", model);
                }
                model.IsRegisterSuccess = true;
                model.IsSendMail = true;
                BackgroundJobs.SendMail.EnqueueRegister(model.Username, "Email xác nhận tài khoản", domainName, verifyLink);
                return PartialView("~/Views/Partials/User/SignUp/_Form.cshtml", model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
        [HttpPost]
        public ActionResult Logout()
        {
            var culture = CultureInfo.CurrentCulture;
            var currentHomePage = Services.ContentService.GetRootContent().First(x => x.GetCulture().Name == culture.Name);
            var link = "/";
            if (currentHomePage != null)
            {
                link = new RenderModel(Umbraco.TypedContent(currentHomePage.Id), culture).Content.Url;
            }
            Members.Logout();
            return Redirect(link);
        }
    }
}

ThuanTanUmbraco/Controllers/ProductController.cs
using System.Globalization;
using System.Web.Mvc;
using ThuanTanUmbraco.Models;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace ThuanTanUmbraco.Controllers
{
    public class ProductController : SurfaceController
    {
        public ActionResult RenderProductItem(int id, string color)
        {
            var model = new RenderModel(Umbraco.TypedContent(id), CultureInfo.CurrentUICulture);
            var productModel = new Product
            {
                RenderProduct = model,
                Color = color
            };
            return PartialView("/Views/Partials/Product/_ImagesWithColor.cshtml", productModel);
        }
    }
}

ThuanTanUmbraco/Controllers/VerifySignUpController.cs
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using ThuanTanUmbraco.ClassHelper;
using Umbraco.Core.Models;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace ThuanTanUmbraco.Controllers
{
    public class VerifySignUpController : SurfaceController
    {
        // GET: VerifySignUp
        public ActionResult Verify(string query)
        {
            if (!string.IsNullOrEmpty(query))
            {
                ViewBag.IsHasQuery = true;
                var email = CryptoHelper.DecryptString(query);
                ViewBag.Email = email;
                var member = Services.MemberService.GetByEmail(email);
                if (member != null)
                {
                    member.IsApproved = true;
                    Services.MemberService.Save(member);
                    ViewBag.IsSuccess = true;
                    ViewBag.ResponseText = "Xác thực email thành công. Bạn vui lòng đăng nhập để tiếp tục.";
                    var culture = CultureInfo.CurrentCulture;
                    var currentHomePage = Services.ContentService.GetRootContent().First(x => x.GetCulture().Name == culture.Name);
                    var signInLink = currentHomePage?.Children().FirstOrDefault(x => x.ContentType.Alias == "memberInfo")?.Children().FirstOrDefault(x => x.ContentType.Alias == "signIn");
                    ViewBag.SignInLink = signInLink != null ? new RenderModel(Umbraco.TypedContent(signInLink.Id), culture).Content.Url : "#";
                    return PartialView("~/Views/Partials/VerifySignUp/_Verify.cshtml");
                }
                ViewBag.IsSuccess = false;
                ViewBag.ResponseText = "Đã có lỗi xảy ra trong quá trình xác thực email. Vui lòng liên hệ quản trị viên để được hỗ trợ.";
            }
            ViewBag.IsHasQuery = false;
            return PartialView("~/Views/Partials/VerifySignUp/_Verify.cshtml");
        }
    }
}

ThuanTanUmbraco/Views/CheckOut.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@Html.Action("CheckSessionCart","CheckOut")

ThuanTanUmbraco/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var home = Model.Content;
    var product = Model.Content.Site().FirstChild("product");
}
@Html.Partial("~/Views/Partials/Layout/_Banner.cshtml")
@if (product != null)
{
    <div class="default-product">
        <div class="container">
            <div class="wings-title">
                <h1>@product.Name</h1>
            </div>
            <div class="row">
                @foreach (var item in product.Children)
                {
                    var thumb = Umbraco.TypedMedia(item.GetPropertyValue<int>("image"));
                    <div class="col-md-4">
                        <div class="item__grid--1">
                            <a href="@item.Url">
                                <img src="@(thumb != null ? thumb.GetCropUrl(370, 330, furtherOptions: "&slimmage=true") : "https://via.placeholder.com/370x330")" alt="@item.Name" />
                            </a>
                            <div class="read-more__main">
                                <a href="@item.Url">@item.Name <i class="fa fa-chevron-right"></i></a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
}
<div class="default-about">
    <div class="container">
        @{ 
            var aboutImage = Umbraco.TypedMedia(home.GetPropertyValue<int>("aboutImage"));
        }
        <div class="row">
            <div class="col-md-4">
                <img class="img-fluid" src="@(aboutImage != null ? aboutImage.GetCropUrl(282, 250, furtherOptions: "&slimmage=true") : "/images/about.png")" alt="" />
            </div>
            <div class="col-md-8">
                <div class="text-justify">
                    @home.GetPropertyValue("aboutContent")
                </div>
            </div>
        </div>
    </div>
</div>

ThuanTanUmbraco/Views/ListProducts.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@Html.Partial("~/Views/Partials/Layout/_BreadCrumb.cshtml")
<div class="wrap-product">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                @Html.Partial("~/Views/Partials/Product/_aside.cshtml")
            </div>
            <div class="col-md-9">
                @Html.Partial("~/Views/Partials/Product/_ProductItems.cshtml")
            </div>
        </div>
    </div>
</div>

ThuanTanUmbraco/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <link href="/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/libs/owl-carousel/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="/libs/malihu/css/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="/css/toastr.min.css" rel="stylesheet" />
    <link href="/css/fonts.css" rel="stylesheet" />
    <link href="/images/mysprite.sprite.css" rel="stylesheet" />
    <link href="/css/site.css" rel="stylesheet" />
    <link href="/css/custom-master.css" rel="stylesheet" />
    <script src="/scripts/jquery.min.js"></script>
    @Html.Partial("~/Views/Partials/Layout/_Share.cshtml")
</head>
<body>
    <div id="wrapper">
        <div id="wrapper-in">
            @Html.Partial("~/Views/Partials/Layout/_Header.cshtml")
            <div id="mobile-overlay"></div>
            <div id="main-content">
                @RenderBody()
            </div>
            @Html.Partial("~/Views/Partials/Layout/_Footer.cshtml")
        </div>
        <div id="menumobile" class="mobile-panel mobilep-left">
            <div class="menu-in">
                <div class="menu-mobile">
                    <div class="logo">
                        <a id="A2" href="/">
                            <img class="img-fluid" src="/images/logo.png" alt="logo" />
                        </a>
                    </div>
                    <ul id="menuMobiles" class="menu-nav"></ul>
                </div>
            </div>
        </div>
    </div>
    <div class="loading_div"></div>
    <a href="#" class="scroll-to-top"></a>
    <script src="/Scripts/popper.min.js"></script>
    <script src="/scripts/bootstrap.min.js"></script>
    <script src="/scripts/jquery.panel.mobile.js"></script>
    <script src="/libs/owl-carousel/scripts/owl.carousel.min.js"></script>
    <script src="/libs/malihu/scripts/jquery.mCustomScrollbar.min.js"></script>
    <script src="/Scripts/sweetalert.min.js"></script>
    <script src="/Scripts/toastr.min.js"></script>

    <script src="/scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="/scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="/scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>

    <script src="/Scripts/cartController.js"></script>
    <script src="/Scripts/filterProductController.js"></script>

    <script src="/scripts/jquery.main.js"></script>

</body>
</html>

ThuanTanUmbraco/Views/MemberInfo.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@if (Members.IsLoggedIn())
{
    <p>Đã login</p>
}
else
{
    <script type="text/javascript">
        window.location = "@CurrentPage.AncestorOrSelf(1).Url";
    </script>
}

ThuanTanUmbraco/Views/News.cshtml
@using Umbraco.Web.Models
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var items = (IEnumerable<IPublishedContent>)CurrentPage.Children().Where("Visible");
    var child = items.OrderByDescending(x => x.SortOrder).ToList();
    var pageSize = 12;

    var page = 1; int.TryParse(Request.QueryString["page"], out page);
    var totalPages = (int)Math.Ceiling((double)child.Count() / (double)pageSize);

    if (page > totalPages)
    {
        page = totalPages;
    }
    else if (page < 1)
    {
        page = 1;
    }
    var banners = (List<IPublishedContent>)CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("banner");
}
@if (banners != null)
{
    <div class="main-banner owl-carousel">
        @foreach (var banner in banners)
        {
            <div class="item">
                <img src="@banner.GetCropUrl(1260, 550, furtherOptions: "&slimmage=true")" alt="" />
            </div>
        }
    </div>
}
@Html.Partial("~/Views/Partials/Layout/_BreadCrumb.cshtml")
<div class="container" style="margin-top: 30px;">
    <h1 class="title-main">@CurrentPage.Name</h1>
    <div class="row">
        @foreach (var item in child.Skip((page - 1) * pageSize).Take(pageSize))
        {
            var thumb = Umbraco.TypedMedia(item.GetPropertyValue<int>("image"));
            <div class="col-md-4">
                <div class="item__news--1">
                    <div class="img">
                        <a href="@item.Url">
                            <img src="@(thumb != null ? thumb.GetCropUrl(360, 263, furtherOptions: "&slimmage=true") : "https://via.placeholder.com/360x263")" alt="" />
                        </a>
                    </div>
                    <div class="content">
                        <a href="@item.Url" title="@item.Name">@Umbraco.Truncate(item.Name, 70)</a>
                        <div class="desc">
                            @Umbraco.Truncate(item.GetPropertyValue<string>("description"), 170)
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    @if (totalPages > 1)
    {
        <div class="pager text-center">
            @if (page > 1)
            {
                <a class="prev" href="?page=@(page-1)"><i class="fa fa-angle-left"></i></a>
            }
            @for (int p = 1; p < totalPages + 1; p++)
            {
                <a class="@(p == page ? "current" : string.Empty)" href="?page=@p">@p</a>
            }
            @if (page < totalPages)
            {
                <a class="next" href="?page=@(page+1)"><i class="fa fa-angle-right"></i></a>
            }
        </div>
    }
</div>

ThuanTanUmbraco/Views/PolicyItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var parent = CurrentPage.Parent();
    var banners = (List<IPublishedContent>)parent.GetPropertyValue<IEnumerable<IPublishedContent>>("banner");
}

@if (banners != null)
{
    <div class="main-banner owl-carousel">
        @foreach (var banner in banners)
        {
            <div class="item">
                <img src="@banner.GetCropUrl(1260, 550, furtherOptions: "&slimmage=true")" alt="" />
            </div>
        }
    </div>
}
@Html.Partial("~/Views/Partials/Layout/_BreadCrumb.cshtml")
<div class="w-930 w-custom">
    <h2 id="news-name">@CurrentPage.Name</h2>
    <div class="wrap-content">
        @CurrentPage.GetPropertyValue("content")
    </div>
</div>

ThuanTanUmbraco/Views/SignUp.cshtml
@using ThuanTanUmbraco.Models
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var node = (IPublishedContent)CurrentPage;
}
@Html.Partial("~/Views/Partials/Layout/_BreadCrumb.cshtml")
<div class="wrap-sign">
    <div class="container">
        <div class="title-product">
            <h1>@node.Name</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="wrap-user__login">
                    @using (Ajax.BeginForm("MemberSignUp",
                        "MemberFrontEnd",
                        null,
                        new AjaxOptions
                        {
                            UpdateTargetId = "signUpAjax",
                            HttpMethod = "POST",
                            OnSuccess = "onSuccess",
                            OnFailure = "onFailure"
                        }, new { @class = "ajaxForm" }))
                    {
                        <div id="signUpAjax">
                            @Html.Partial("~/Views/Partials/User/SignUp/_Form.cshtml", new RegisterForm())
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ThuanTanUmbraco/Views/VerifySignUp.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var home = CurrentPage.AncestorOrSelf(1);
    var banners = home.GetPropertyValue<IEnumerable<IPublishedContent>>("banners");
}
@if (banners != null && banners.Any())
{
    <div class="main-banner owl-carousel">
        @foreach (var item in banners)
        {
            var thumb = Umbraco.TypedMedia(item.GetPropertyValue<int>("image"));
            <div class="item">
                <img src="@(thumb != null ? thumb.GetCropUrl(1260, 550, furtherOptions: "&slimmage=true") : "https://via.placeholder.com/1260x550")" alt="" />
                <div class="banner-content">
                    <div class="container">
                        <div class="banner-content__wrap">
                            <h1 class="title">@item.GetPropertyValue("bannerTitle")</h1>
                            <div class="desc">
                                @item.GetPropertyValue("bannerDescription")
                            </div>
                            <div class="read-more__main">
                                <a href="@item.GetPropertyValue("bannerLink")">Discover <i class="fa fa-chevron-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
@Html.Action("Verify", "VerifySignUp", Request.Params["query"])

ThuanTanUmbraco/Views/visitor.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@

ThuanTanUmbraco/Views/visitorItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@